name: Deploy to Amazon Amplify
on:
  push:
    branches: [ ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Amplify Production
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.AMPLIFY_WEBHOOK_URL }}
