name: Deploy to Amazon Amplify
on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Amplify Production
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.AMPLIFY_WEBHOOK_URL }}
